version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.0
  env_file:
    - ../config/airflow.env
  environment:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: clima_brasil
    POSTGRES_USER: clima_user
    POSTGRES_PASSWORD: clima_pass
  volumes:
    - ../dags:/opt/airflow/dags
    - ../logs:/opt/airflow/logs
    - ../plugins:/opt/airflow/plugins
    - ../src:/opt/airflow/src
    - ../data:/opt/airflow/data
    - ../sql:/opt/airflow/sql
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16-alpine
    container_name: clima_brasil_db
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clima_user -d clima_brasil"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: clima_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clima.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  airflow-init:
    <<: *airflow-common
    container_name: clima_airflow_init
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin123 --firstname Admin --lastname User --role Admin --email admin@clima.com"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    container_name: clima_airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: clima_airflow_scheduler
    command: scheduler
    restart: always

volumes:
  pgdata: