services:
  postgres:
    image: postgres:16-alpine
    container_name: clima_brasil_db
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clima_user -d clima_brasil"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: clima_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clima.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata: