services:
  postgres:
    image: postgres:16-alpine
    container_name: clima_brasil_db
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clima_user -d clima_brasil"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: